"""
Django settings for ShoppingMall2 project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=$1poxk5q_6+5olqq$-=ubw^y0dmpph^p861-7_m3+l2wmocb#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'User.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'Item.apps.ItemConfig',
    'User.apps.UserConfig',
    'corsheaders',
    'oauth2_provider',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ShoppingMall2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ShoppingMall2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'point_mall',
        'USER': 'root',
        'PASSWORD': 'clqls4013*',
        'HOST': 'point-mall.cbsoxrvgvaj7.us-east-1.rds.amazonaws.com',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

CORS_ORIGIN_ALLOW_ALL = True


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
}

AWS_ACCESS_KEY_ID = 'ASIAQXKTM523AJN5M7GT'
AWS_SECRET_ACCESS_KEY = '/BNi4O75xFEBiGQkhJnDBOoAHTnE/Xzl/ra6uYrZ'
AWS_SESSION_TOKEN = 'FQoGZXIvYXdzEFoaDO4BhTg21ICxTTn8RCL/AWlD1tPXGqWZ342IcoMWX/CZtEeusnFLcz2iTuwu68ByROYw/Ln6Fa5rslu1zTWqlW1GVjzflnUAqXwnofhUYglcp3mGMydh1xP9ByITOYOUbPQdEgjYgWqjry+KeNf8JTJKb1QysiBwcJ++o+L5vZWLBQNiRuhvruQ3uy4d8IffLBC3I0UxEuZb9plzILeQVmIp8DyAAJV2mRTtTYbcD34TTPlKwTjsx8ooJjMIgcUAgYoF0//T/qe64fUTsFc3ZEQL2BPVZ4tGy+zrlS8307JlPnxStO1s3nrNG5wQPTZvmaVS85mNyCUWuVStVLwrn9QF32TbzfBiq6614HtI9yi15vzqBQ=='

AWS_STORAGE_BUCKET_NAME = 'cdn.pointmall.scv' # 버킷이름
AWS_S3_CUSTOM_DOMAIN = 'd39dy2hcyi57ic.cloudfront.net'    #cloude front의 도메인
AWS_S3_URL = 'https://%s/' % AWS_S3_CUSTOM_DOMAIN
AWS_S3_SIGNATURE_VERSION = 's3v4'

STATIC_URL = '/static/'
STATIC_ROOT = 'static/'
STATICFILES_STORAGE = 'ShoppingMall2.storages.StaticStorage'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_LOCATION = 'assets/'
ASSET_URL = '%s%s' % (AWS_S3_URL, AWS_LOCATION)

# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'ShoppingMall2.storages.FilesStorage'

MEDIA_ROOT = 'media/'
MEDIA_URL = '/media/'
