# Generated by Django 2.2.3 on 2019-08-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_auto_20190725_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
